version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: app/Dockerfile  
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
   
    environment:
      - MONGO_URI=mongodb://mongodb:27017/pension_funds
    

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
